# Generated by Django 2.2.5 on 2019-09-27 12:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
                ('write_date', models.DateTimeField(blank=True, null=True, verbose_name='Last modified')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('description', models.TextField(verbose_name='Description')),
                ('priority', models.IntegerField(choices=[(1, 'High'), (2, 'Normal'), (3, 'Low')], default=2, verbose_name='Priority')),
                ('starred', models.BooleanField(default=False, verbose_name='Starred')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_uid', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_create_uid', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitter_uid', to=settings.AUTH_USER_MODEL, verbose_name='Submitter')),
                ('write_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_write_uid', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
            ],
            options={
                'db_table': 'openticketing_ticket',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
                ('write_date', models.DateTimeField(blank=True, null=True, verbose_name='Last modified')),
                ('note', models.TextField(verbose_name='Note')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_create_uid', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.Ticket', verbose_name='Comment')),
                ('write_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_write_uid', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
