# Generated by Django 2.2.5 on 2020-01-26 06:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('write_date', models.DateTimeField(blank=True, null=True, verbose_name='Last modified')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('description', models.TextField(verbose_name='Description')),
                ('priority', models.IntegerField(choices=[(1, 'High'), (2, 'Normal'), (3, 'Low')], default=2, verbose_name='Priority')),
                ('status', models.IntegerField(choices=[(1, 'Draft'), (2, 'Open'), (3, 'Closed'), (4, 'Pending')], default=1, verbose_name='Status')),
                ('starred', models.BooleanField(default=False, verbose_name='Starred')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_uid', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to')),
            ],
            options={
                'db_table': 'ot_ticket',
            },
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('write_date', models.DateTimeField(blank=True, null=True, verbose_name='Last modified')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticketcategory_create_uid', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('write_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticketcategory_write_uid', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
            ],
            options={
                'verbose_name': 'Ticket category',
                'db_table': 'ot_category',
            },
        ),
        migrations.CreateModel(
            name='TicketAttachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('write_date', models.DateTimeField(blank=True, null=True, verbose_name='Last modified')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('doc_file', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticketattachments_create_uid', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.Ticket', verbose_name='Ticket')),
                ('write_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticketattachments_write_uid', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
            ],
            options={
                'db_table': 'ot_ticket_attachments',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.TicketCategory', verbose_name='Help Topics'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='create_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_create_uid', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_app.Department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='dependecies',
            field=models.ManyToManyField(blank=True, related_name='_ticket_dependecies_+', to='tickets.Ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_app.Organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitter_uid', to=settings.AUTH_USER_MODEL, verbose_name='Submitter'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='write_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_write_uid', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('write_date', models.DateTimeField(blank=True, null=True, verbose_name='Last modified')),
                ('note', models.TextField(verbose_name='Note')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_create_uid', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.Ticket', verbose_name='Ticket')),
                ('write_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_write_uid', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
            ],
            options={
                'db_table': 'ot_comment',
            },
        ),
    ]
