# Generated by Django 2.2.5 on 2020-01-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default=' ', max_length=128, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
