# Generated by Django 2.2.5 on 2020-01-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='dependecies',
        ),
        migrations.AddField(
            model_name='ticket',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='_ticket_dependencies_+', to='tickets.Ticket'),
        ),
    ]
