# Generated by Django 2.2.5 on 2020-01-18 14:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0004_auto_20200115_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcategory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='TicketAttachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('write_date', models.DateTimeField(blank=True, null=True, verbose_name='Last modified')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('doc_file', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticketattachments_create_uid', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.Ticket', verbose_name='Ticket')),
                ('write_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticketattachments_write_uid', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
            ],
            options={
                'db_table': 'openticketing_ticket_attachments',
            },
        ),
    ]
