# Generated by Django 2.2.5 on 2020-01-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20200118_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='dependecies',
            field=models.ManyToManyField(blank=True, related_name='_ticket_dependecies_+', to='tickets.Ticket'),
        ),
    ]
